# Define the rules to scan for
[[rules]]
description = "Generic API Key"
regex = '''(api|secret|key|token)[\s]*=[\s]*['"][^'"]{32,}['"]'''
tags = ["apikey", "generic"]
severity = "HIGH"

# Include .env file in scan
[[files]]
pattern = "**/.env"

# Allowlist for files to exclude from scanning
[allowlist]
paths = [
  "\\.env$",
  "Dockerfile$"
]

# Scan all files
[scan]
# This includes all files, even those not tracked in git
include = [
  "**/*.js",
  "**/*.ts",
  "**/.env",
  "**/*.yaml",
  "**/*.yml"
]

verbose = true