name: Salary API CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: source-code

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: source-code

  sonar-scan:
    runs-on: ubuntu-latest
    needs: clone
    container:
      image: maven:3.9-eclipse-temurin-17
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: source-code

      - name: Run Maven Compile
        run: |
          cd source-code
          mvn clean compile -DskipTests

      - name: Run Maven Sonar Scan
        run: |
          cd source-code
          mvn sonar:sonar \
            -DskipTests \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectName=${{ github.event.repository.name }} \
            -Dsonar.projectKey=${{ github.event.repository.name }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.qualitygate.wait=true
