name: Salary API CI pipeline

on:
  push:
    branches: [ "main" ]


permissions:
    id-token: write
    contents: read  
    packages: write
    
jobs:

  pre_checks:
   uses: NavabShariff/shared-library/.github/workflows/pre-checks.yml@main
   with:
     fail: 'true'
     verbose: 'true'
     redact: 'true'
     commit_sign_off: 'true'
     commit_message: 'false'
     upload_artifacts: true
     artifact_name: 'source-code'


  # build:
  #   uses: NavabShariff/shared-library/.github/workflows/maven-build.yml@main
  #   with:
  #     java_version: '17'
  #     mvn_command: clean compile -DskipTests
  #     upload_artifacts: true
  #     artifact_name: ${{ github.event.repository.name }}

  # sast:
  #   needs: build
  #   uses: NavabShariff/shared-library/.github/workflows/sonar-scanning-java.yml@main
  #   secrets:
  #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #   with: 
  #     download_artifacts: true
  #     artifact_name: ${{ github.event.repository.name }}
  #     qualitygate: false

  # docker-image-build:
  #   needs: [sast]
  #   uses: NavabShariff/shared-library/.github/workflows/docker-login-build-push-ecr.yml@main
  #   with:
  #     ecr_repo: 'salary-api'
  #     aws_region: 'ap-south-1'
  #     download_artifacts: true
  #     artifact_name: ${{ github.event.repository.name }}
  #   secrets:
  #     AWS_IAM_ROLE_ATHENTICATION: ${{ secrets.AWS_IAM_ROLE_ATHENTICATION }}


  # docker-image-scan:
  #   needs: [docker-image-build]
  #   uses: NavabShariff/shared-library/.github/workflows/ecr-image-scan.yml@main
  #   with:
  #     ecr_repo: 'salary-api'
  #     aws_region: 'ap-south-1'
  #     download_artifacts: true
  #     artifact_name: ${{ github.event.repository.name }}
  #   secrets:
  #     AWS_IAM_ROLE_ATHENTICATION: ${{ secrets.AWS_IAM_ROLE_ATHENTICATION }}


  # trigger-cd:
  #   needs: [docker-image-scan]
  #   uses: NavabShariff/shared-library/.github/workflows/gitops-update-source-truth.yml@main
  #   with:
  #     gitops_repo: "NavabShariff/gitops-source"
  #   secrets:
  #     GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # notify:
  #   uses: NavabShariff/shared-library/.github/workflows/send-slack-alert.yml@main
  #   needs: [build, sast, docker-image-build, docker-image-scan, trigger-cd]
  #   if: always()
  #   with:
  #     status: ${{ contains(join(needs.*.result, ' '), 'failure') && 'failure' || 'success' }}
  #     commit_author_name: ${{ github.event.pusher.name }}
  #     commit_message: ${{ github.event.head_commit.message }}
  #     commit_id: ${{ github.sha }}
  #     run_id: ${{ github.run_id }}
  #   secrets:
  #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
