name: Salary API Pipeline

on:
  push:
    branches: [ "main" ]

env:
  coverage_report_path: 'jacoco.xml'
  qualityGateWait: 'false'
  language: 'java'

jobs:

  sonar-scan:

    runs-on: ubuntu-latest

    container:
      image: maven:3.9-eclipse-temurin-17

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Maven Build and SonarQube Scan
        uses: NavabShariff/shared-library/.github/actions/sonar-scan@main
        with:
          language: ${{ env.language }}
          projectName: ${{ github.event.repository.name }}
          projectKey: ${{ github.event.repository.name }}
          sonarHostUrl: ${{ secrets.SONAR_HOST_URL }}
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          coverageReportPath: ${{ env.coverage_report_path }}
          qualityGateWait: ${{ env.qualityGateWait }}