name: Salary API Pipeline

on:
  push:
    branches: [ "main" ]

env:
  coverage_report_path: 'jacoco.xml'
  qualityGateWait: 'false'
  language: 'java'

jobs:

  # sonar-scan:

  #   runs-on: ubuntu-latest

  #   container:
  #     image: maven:3.9-eclipse-temurin-17

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Run Maven Build and SonarQube Scan
  #       uses: NavabShariff/shared-library/.github/actions/sonar-scan@main
  #       with:
  #         language: ${{ env.language }}
  #         projectName: ${{ github.event.repository.name }}
  #         projectKey: ${{ github.event.repository.name }}
  #         sonarHostUrl: ${{ secrets.SONAR_HOST_URL }}
  #         sonarToken: ${{ secrets.SONAR_TOKEN }}
  #         coverageReportPath: ${{ env.coverage_report_path }}
  #         qualityGateWait: ${{ env.qualityGateWait }}

  docker-build-and-push:
    runs-on: ubuntu-latest
    # needs: sonar-scan

    steps:
      - uses: actions/checkout@v4

      - name: Set image name and tag
        run: |
          echo "commit_sha=$(echo $GITHUB_SHA | head -c 8)" >> $GITHUB_ENV
          ORG_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          echo "image_name=ghcr.io/$ORG_NAME/$REPO_NAME" >> $GITHUB_ENV


      - name: Docker Build
        uses: NavabShariff/shared-library/.github/actions/docker-build@main
        with:
          image_name: ${{ env.image_name }}
          tags: ${{ env.commit_sha }}

      - name: Docker Login and Push
        uses: NavabShariff/shared-library/.github/actions/docker-login-push@main
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ env.image_name }}
          tag: ${{ env.commit_sha }}